server:
    port: 9090
spring:
    data:
        mongodb:
            uri: ${MONGO_URI}
logging:
    file:
        path: logs

management:
    endpoints:
        jmx:
            exposure:
                exclude: "*"
        web:
            exposure:
                include: health
            base-path: ${ACTUATOR_PATH}
        health:
            enabled: true
heroku:
    server: ${HEROKU_API_SERVER}
    health: ${heroku.server}${ACTUATOR_PATH}/health
