server:
    port: 9090
spring:
    data:
        mongodb:
            uri: ${MONGO_URI}
logging:
    file:
        path: logs

management:
    server:
        port: ${ACTUATOR_PORT}
    endpoints:
        jmx:
            exposure:
                exclude: "*"
        web:
            exposure:
                include: health
            base-path: ${ACTUATOR_PATH}
        health:
            enabled: true
