server:
    port: 9090
    tomcat:
        mbeanregistry:
            enabled: true
spring:
    config:
        import: optional:file:.env[.properties]
    data:
        mongodb:
            uri: ${MONGO_URI}
    jackson:
        default-property-inclusion: NON_EMPTY
logging:
    file:
        path: logs
management:
    info:
        java:
            enabled: true
        os:
            enabled: true
        env:
            enabled: true
    endpoint:
        shutdown:
            enabled: true
        health:
            show-components: always
    endpoints:
        web:
            exposure:
                include: "*"
            base-path: ${ACTUATOR_PATH}
        health:
            enabled: true
heroku:
    server: ${HEROKU_API_SERVER}
    health: ${heroku.server}${ACTUATOR_PATH}/health
document:
    path: ${api.path}
notification:
    slack-url: ${SLACK_URL}
    lunch-slack-url: ${LUNCH_SLACK_URL}
